### ISSUE TITLE
A stuck problem during the pre-training

### ISSUE THREAD

**Issue by HenryHZY** [jayleicn/mTVRetrieval#2]
# The third bug, an error?
By the way, my computer also encountered a stuck problem during the pre-training and I had to restart it. 

But when I checked the log file, I found that it successfully produced the `model.ckpt` and
```
en_best_tvr_val_predictions_VCMR_SVMR_VR.json
en_best_tvr_val_predictions_VCMR_SVMR_VR_metrics.json
zh_best_tvr_val_predictions_VCMR_SVMR_VR.json
zh_best_tvr_val_predictions_VCMR_SVMR_VR_metrics.json
en_latest_tvr_val_predictions_VCMR_SVMR_VR.json
en_latest_tvr_val_predictions_VCMR_SVMR_VR_metrics.json
zh_latest_tvr_val_predictions_VCMR_SVMR_VR.json
zh_latest_tvr_val_predictions_VCMR_SVMR_VR_metrics.json
en_inference_tvr_val_None_predictions_SVMR_VCMR_VR.json
en_inference_tvr_val_None_predictions_SVMR_VCMR_VR_metrics.json
en_inference_tvr_val_None_predictions_SVMR_VCMR_VR_nms_thd_0.5.json
```

I think there may be two reasons for that:
1. My gpu and memory resources are insufficient
2. There is a bug when producing the following files:
```
zh_inference_tvr_val_None_predictions_SVMR_VCMR_VR.json
zh_inference_tvr_val_None_predictions_SVMR_VCMR_VR_metrics.json
zh_inference_tvr_val_None_predictions_SVMR_VCMR_VR_nms_thd_0.5.json
```

**Comment by jayleicn** [comment]
Could you provide more context on how and where this happens?

**Comment by HenryHZY** [comment]
> Could you provide more context on how and where this happens?

@jayleicn Since the computer suddenly stuck and crashed for two days, I could only make a judgment based on the log file after restarting, so no related error messages were recorded. 
I will try to reproduce this error when I am free later. Thanks for your quick reply. :)
